/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    "./app/**/*.{js,jsx,ts,tsx}", 
    "./components/**/*.{js,jsx,ts,tsx}",
    "./context/**/*.{js,jsx,ts,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        // ── Brand shortcuts ──────────────────────────────────────────
        'brand-bg':                   '#0d1516',
        'brand-surface':              '#0d1516',
        'brand-card':                 '#192122',
        'brand-input':                '#252525',
        'brand-neon':                 '#00e5ff',
        'brand-neon-dim':             '#00daf3',
        'brand-outline':              '#849396',
        'brand-outline-variant':      '#3b494c',
        'brand-on-surface':           '#dce4e5',
        'brand-on-surface-variant':   '#bac9cc',
        'brand-success':              '#7dffa2',
        'brand-warning':              '#ffecac',
        'brand-warning-container':    '#f5cd00',
        'brand-error':                '#ffb4ab',
        // ── Full M3 Design Token Mapping ─────────────────────────────
        'surface':                    '#0d1516',
        'surface-dim':                '#0d1516',
        'surface-bright':             '#333a3c',
        'surface-container-lowest':   '#080f11',
        'surface-container-low':      '#151d1e',
        'surface-container':          '#192122',
        'surface-container-high':     '#242b2d',
        'surface-container-highest':  '#2e3638',
        'on-surface':                 '#dce4e5',
        'on-surface-variant':         '#bac9cc',
        'inverse-surface':            '#dce4e5',
        'inverse-on-surface':         '#2a3233',
        'outline':                    '#849396',
        'outline-variant':            '#3b494c',
        'surface-tint':               '#00daf3',
        'primary':                    '#c3f5ff',
        'on-primary':                 '#00363d',
        'primary-container':          '#00e5ff',
        'on-primary-container':       '#00626e',
        'inverse-primary':            '#006875',
        'secondary':                  '#7dffa2',
        'on-secondary':               '#003918',
        'secondary-container':        '#05e777',
        'on-secondary-container':     '#00622e',
        'tertiary':                   '#ffecac',
        'on-tertiary':                '#3a3000',
        'tertiary-container':         '#f5cd00',
        'on-tertiary-container':      '#695700',
        'error':                      '#ffb4ab',
        'on-error':                   '#690005',
        'error-container':            '#93000a',
        'on-error-container':         '#ffdad6',
        'primary-fixed':              '#9cf0ff',
        'primary-fixed-dim':          '#00daf3',
        'on-primary-fixed':           '#001f24',
        'on-primary-fixed-variant':   '#004f58',
        'secondary-fixed':            '#62ff96',
        'secondary-fixed-dim':        '#00e475',
        'on-secondary-fixed':         '#00210b',
        'on-secondary-fixed-variant': '#005226',
        'tertiary-fixed':             '#ffe170',
        'tertiary-fixed-dim':         '#e9c400',
        'on-tertiary-fixed':          '#221b00',
        'on-tertiary-fixed-variant':  '#544600',
        'background':                 '#0d1516',
        'on-background':              '#dce4e5',
        'surface-variant':            '#2e3638',
      },
    },
  },
  plugins: [],
}